server {
    listen 80;
    listen [::]:80;
    server_name localhost;

    # 1. Redirection des requêtes API vers le backend Kubernetes
    location /api/ {
        # REMPLACE "backend-service" PAR LE NOM DU SERVICE K8S DE TON COLLEGUE
        proxy_pass http://backend-service:8080/api/;
    }

    # 2. Distribution de ton application Vue.js
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # La ligne magique pour que Vue Router fonctionne :
        try_files $uri $uri/ /index.html;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}