/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/page1': RouteRecordInfo<'/page1', '/page1', Record<never, never>, Record<never, never>>,
    '/page2': RouteRecordInfo<'/page2', '/page2', Record<never, never>, Record<never, never>>,
    '/page3': RouteRecordInfo<'/page3', '/page3', Record<never, never>, Record<never, never>>,
    '/page4': RouteRecordInfo<'/page4', '/page4', Record<never, never>, Record<never, never>>,
    '/page5': RouteRecordInfo<'/page5', '/page5', Record<never, never>, Record<never, never>>,
    '/page6': RouteRecordInfo<'/page6', '/page6', Record<never, never>, Record<never, never>>,
    '/page7': RouteRecordInfo<'/page7', '/page7', Record<never, never>, Record<never, never>>,
    '/page8': RouteRecordInfo<'/page8', '/page8', Record<never, never>, Record<never, never>>,
    '/page9': RouteRecordInfo<'/page9', '/page9', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/page1.vue': {
      routes: '/page1'
      views: never
    }
    'src/pages/page2.vue': {
      routes: '/page2'
      views: never
    }
    'src/pages/page3.vue': {
      routes: '/page3'
      views: never
    }
    'src/pages/page4.vue': {
      routes: '/page4'
      views: never
    }
    'src/pages/page5.vue': {
      routes: '/page5'
      views: never
    }
    'src/pages/page6.vue': {
      routes: '/page6'
      views: never
    }
    'src/pages/page7.vue': {
      routes: '/page7'
      views: never
    }
    'src/pages/page8.vue': {
      routes: '/page8'
      views: never
    }
    'src/pages/page9.vue': {
      routes: '/page9'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
